// Generated by IcedCoffeeScript 1.3.1b
(function() {

  exports.affine = require('./lib/affine');

  exports.vector = require('./lib/vector');

  exports.polygon = require('./lib/polygon');

}).call(this);
