// Generated by IcedCoffeeScript 1.3.1b
(function() {
  var vector;

  vector = (function() {

    vector.name = 'vector';

    function vector(v0, v1) {
      this.v0 = v0;
      this.v1 = v1;
    }

    vector.prototype.copy = function() {
      return new vector(this.v0, this.v1);
    };

    vector.prototype.transform = function(aff) {
      var t0, t1;
      t0 = aff.m00 * this.v0 + aff.m01 * this.v1 + aff.v0;
      t1 = aff.m10 * this.v0 + aff.m11 * this.v1 + aff.v1;
      this.v0 = t0;
      this.v1 = t1;
      return this;
    };

    vector.prototype.scale = function(s) {
      this.v0 *= s;
      this.v1 *= s;
      return this;
    };

    return vector;

  })();

  exports.vector = vector;

}).call(this);
